"""
config.py — Constants, i18n strings, patterns.
No dependencies on other project modules.
"""

C_BG        = "#000000"
C_FG        = "#ffffff"
C_FG_DIM    = "#a0a0a0"
C_RED       = "#ff0000"
C_RED_DIM   = "#7a0000"
C_RED_SEL   = "#3a0000"
C_RED_HOVER = "#cc0000"

F_TITLE  = ("Arial", 14, "bold")
F_SUB    = ("Arial", 9)
F_NORM   = ("Arial", 10)
F_SMALL  = ("Arial", 9)
F_BTN    = ("Arial", 10, "bold")
F_HEAD   = ("Arial", 10, "bold")
F_LOG    = ("Courier New", 9)
F_ROW    = ("Arial", 10, "bold")
F_ROW_S  = ("Arial", 9)

APP_NAME = "GMod Addon Manager"
APP_VERSION = "2.0.0"

CONFIG_FILE      = "gmod_manager.json"
CACHE_FILE       = "gmod_cache.json"
SESSION_FILE     = "gmod_session.json"
LOG_FILE         = "gmod_manager.log"
COLLECTIONS_FILE = "gmod_collections.json"
WHITELIST_FILE   = "gmod_whitelist.json"

TEXT_EXTENSIONS = {".txt", ".json", ".lua", ".md", ".cfg", ".ini", ".xml"}

RAW_MARKERS = ("lua/", "materials/", "models/", "sound/",
               "scripts/", "particles/", "scenes/", "resource/")

KNOWN_DEPENDENCIES = {
    r"\bdrgbase\b": "DrGBase",
    r"\bvj_base\b": "VJ Base",
    r"\bvjbase\b": "VJ Base",
    r"\barc[_]?cw\b": "ArcCW",
    r"\barc9\b": "ARC9",
    r"\btfa[_]?base\b": "TFA Base",
    r"\bwiremod\b": "Wiremod",
    r"\bwire[_]?expression[2]?\b": "Wiremod",
    r"\bpac3\b": "PAC3",
    r"\bsimfphys\b": "Simfphys",
    r"\bcfc[_]?player\b": "CFC",
    r"\bnutscript\b": "NutScript",
    r"\bhelix\b": "Helix",
    r"\bsam[_]?admin\b": "SAM",
    r"\bwac[_]?aircraft\b": "WAC",
    r"\bwos[_ ]?dynabase\b": "wOS DynaBase",
    r"\bdynabase\b": "wOS DynaBase",
}

LUA_DEP_HINTS = {
    r"\bif\s+VJ\s+then\b": "VJ Base",
    r"\bif\s+DrGBase\s+then\b": "DrGBase",
    r"\bif\s+ArcCW\s+then\b": "ArcCW",
    r"\bif\s+simfphys\s+then\b": "Simfphys",
    r"\bif\s+CFC\s+then\b": "CFC",
}

LUA_REF_PATTERNS = [
    r'require\s*\(\s*["\']([^"\']+)["\']',
    r'include\s*\(\s*["\']([^"\']+)["\']',
]

GENERIC_REFS = {
    "shared.lua", "init.lua", "cl_init.lua", "sv_init.lua",
    "loader.lua", "sound.lua", "autorun.lua", "config.lua",
    "sh_config.lua", "cl_util.lua", "sv_util.lua", "shared/util.lua",
}

LUA_DANGER_PATTERNS = [
    (r'\bos\.execute\s*\(',        'os.execute (shell)'),
    (r'\bio\.popen\s*\(',          'io.popen (shell)'),
    (r'\bos\.remove\s*\(',         'os.remove (delete file)'),
    (r'\bos\.rename\s*\(',         'os.rename (rename file)'),
    (r'\bRunString[A-Za-z]*\s*\(', 'RunString (dynamic code)'),
    (r'\bCompileString\s*\(',      'CompileString (dynamic code)'),
    (r'\bhttp\.Fetch\s*\(',        'http.Fetch (network)'),
    (r'\bhttp\.Post\s*\(',         'http.Post (network)'),
    (r'STEAM_0:\d+:\d+',           'Hardcoded SteamID'),
    (r'\bfile\.Delete\s*\(',       'file.Delete'),
    (r'\bfile\.Write\s*\(',        'file.Write'),
]

MAX_TEXT_SIZE = 2 * 1024 * 1024
MAX_ZIP_TOTAL = 8 * 1024 * 1024 * 1024
MAX_NESTED_DEPTH = 3
MAX_NESTED_IN_MEM = 300 * 1024 * 1024
FILTER_DEBOUNCE_MS = 150
PARALLEL_WORKERS = 4
WATCH_POLL_SECONDS = 3

DEFAULT_LANG = "en"

STRINGS = {
    "en": {
        "lang_button": "ES",
        "add_panel": "ADD",
        "files_btn": "FILES",
        "folder_btn": "FOLDER",
        "add_btn": "ADD",
        "from_url_btn": "FROM URL",
        "filter_panel": "FILTER",
        "search_label": "Search:",
        "group_dep": "Group by dependency",
        "addons_panel": "ADDONS",
        "all_btn": "ALL",
        "none_btn": "NONE",
        "invert_btn": "INVERT",
        "remove_btn": "REMOVE",
        "clear_btn": "CLEAR",
        "export_btn": "EXPORT",
        "dest_panel": "DESTINATION",
        "choose_btn": "CHOOSE",
        "open_btn": "OPEN",
        "backup_btn": "BACKUP",
        "analyze_btn": "ANALYZE",
        "extract_btn": "EXTRACT",
        "repack_btn": "REPACK",
        "summary_btn": "SUMMARY",
        "conflicts_btn": "CONFLICTS",
        "cancel_btn": "CANCEL",
        "tools_panel": "TOOLS",
        "history_btn": "HISTORY",
        "rename_all_btn": "RENAME ALL",
        "grep_btn": "GREP",
        "watch_btn": "WATCH",
        "collections_btn": "COLLECTIONS",
        "whitelist_btn": "WHITELIST",
        "report_btn": "HTML REPORT",
        "sizes_btn": "SIZES",
        "fastdl_btn": "FASTDL",
        "log_panel": "LOG",
        "copy_btn": "COPY",
        "log_clear_btn": "CLEAR",
        "log_open_btn": "OPEN FILE",
        "close_btn": "CLOSE",
        "ready": "Ready.",
        "working": "Working...",
        "canceling": "Canceling...",
        "empty_title": "Empty",
        "empty_body": "No addons are marked.",
        "no_dest_title": "Missing destination",
        "no_dest_body": "Type or choose the destination folder.",
        "not_found_title": "Not found",
        "not_found_body": "Not found:\n{path}",
        "no_log_title": "Log",
        "no_log_body": "No log file yet.",
        "rename_title": "Rename",
        "rename_prompt": "New name:",
        "rename_all_title": "Rename all",
        "rename_all_prompt": "Pattern (use {i} for index, {name} for old name):",
        "action_title": "Action",
        "action_body": "Addon: {name}\n\nYes = Rename\nNo = Extract to temp and open\nCancel = Nothing",
        "dest_missing_title": "Does not exist",
        "conflicts_need_title": "Conflicts",
        "conflicts_need_body": "Mark at least 2 addons.",
        "conflicts_none_title": "Conflicts",
        "conflicts_none_body": "No conflicts between marked addons.",
        "summary_empty_title": "Summary",
        "summary_empty_body": "Nothing analyzed yet.",
        "export_empty_title": "Export",
        "export_empty_body": "No addons.",
        "save_as_title": "Save as",
        "zip_error_title": "Error reading zip",
        "error_title": "Error",
        "url_title": "Download from Workshop",
        "url_prompt": "Paste the Steam Workshop URL:",
        "url_bad_body": "Could not find a Workshop ID in that URL.",
        "url_ok": "Downloaded: {name}",
        "url_no_file": "Steam did not provide a download URL for this item.",
        "grep_title": "Grep inside addons",
        "grep_prompt": "Search string:",
        "grep_empty": "No matches found.",
        "grep_done": "Found {n} match(es) in {m} addon(s).",
        "repack_title": "Repack to GMA",
        "repack_prompt": "Destination .gma file:",
        "repack_need_folder": "Select exactly one folder to repack.",
        "backup_title": "Backup",
        "backup_done": "Backed up {n} existing addon(s) to {path}.",
        "watch_title": "Watch folder",
        "watch_prompt": "Choose folder to watch:",
        "watch_started": "Watching: {path}",
        "watch_stopped": "Watch stopped.",
        "watch_new": "New file detected: {name}",
        "whitelist_title": "Workshop whitelist",
        "whitelist_body": "IDs allowed (one per line):",
        "collections_title": "Collections",
        "collections_save": "Save current list",
        "collections_load": "Load collection",
        "collections_name": "Collection name:",
        "collections_saved": "Saved: {name}",
        "collections_empty": "No collections saved yet.",
        "report_done": "Report saved: {path}",
        "sizes_title": "Size breakdown",
        "fastdl_title": "FastDL export",
        "fastdl_prompt": "Choose FastDL root folder:",
        "fastdl_done": "Copied {n} asset(s) to {path}.",
        "gmod_open_title": "Garry's Mod appears to be running",
        "gmod_open_body": "GMod should be closed before modifying addons. Continue anyway?",
        "status_analyzing": "Analyzing {i}/{total}: {name}",
        "status_scanning": "Scanning {i}/{total}: {name}",
        "status_extracting": "Extracting {i}/{total}: {name}",
        "status_indexing": "Indexing {i}/{total}: {name}",
        "status_analysis_ok": "Analysis complete: {n} addon(s)",
        "status_analysis_partial": "Analysis: {ok} ok, {fail} error(s)",
        "status_analysis_cancelled": "Analysis cancelled: {n}/{total}",
        "status_extract_ok": "Extraction complete: {n} addon(s)",
        "status_extract_partial": "Extraction: {ok} ok, {fail} failed",
        "status_extract_cancelled": "Extraction cancelled: {ok} ok, {fail} failed",
        "status_index_ok": "Index complete: {n} addon(s)",
        "status_index_cancelled": "Index cancelled: {n} addon(s)",
        "status_conflicts_none": "Conflicts: none",
        "status_conflicts_found": "Conflicts: {n} file(s)",
        "status_selected_all": "Selected {n} addon(s)",
        "status_deselected_all": "Deselected {n} addon(s)",
        "status_inverted": "Selection inverted: {sel} selected",
        "status_removed": "Removed {n} addon(s)",
        "status_cleared": "List cleared ({n} removed)",
        "status_exported": "Exported: {name}",
        "status_session": "Session: {n} addon(s)",
        "status_added_zip": "{name}: {n} addon(s)",
        "status_no_op": "No operation in progress.",
        "status_cancel_requested": "Cancel requested...",
    },
    "es": {
        "lang_button": "EN",
        "add_panel": "AÑADIR",
        "files_btn": "ARCHIVOS",
        "folder_btn": "CARPETA",
        "add_btn": "AÑADIR",
        "from_url_btn": "DESDE URL",
        "filter_panel": "FILTRO",
        "search_label": "Buscar:",
        "group_dep": "Agrupar por dependencia",
        "addons_panel": "ADDONS",
        "all_btn": "TODO",
        "none_btn": "NADA",
        "invert_btn": "INVERTIR",
        "remove_btn": "QUITAR",
        "clear_btn": "LIMPIAR",
        "export_btn": "EXPORTAR",
        "dest_panel": "DESTINO",
        "choose_btn": "ELEGIR",
        "open_btn": "ABRIR",
        "backup_btn": "BACKUP",
        "analyze_btn": "ANALIZAR",
        "extract_btn": "EXTRAER",
        "repack_btn": "REPACK",
        "summary_btn": "RESUMEN",
        "conflicts_btn": "CONFLICTOS",
        "cancel_btn": "CANCELAR",
        "tools_panel": "HERRAMIENTAS",
        "history_btn": "HISTORIAL",
        "rename_all_btn": "RENOMBRAR TODO",
        "grep_btn": "GREP",
        "watch_btn": "VIGILAR",
        "collections_btn": "COLECCIONES",
        "whitelist_btn": "WHITELIST",
        "report_btn": "REPORTE HTML",
        "sizes_btn": "TAMAÑOS",
        "fastdl_btn": "FASTDL",
        "log_panel": "REGISTRO",
        "copy_btn": "COPIAR",
        "log_clear_btn": "LIMPIAR",
        "log_open_btn": "ABRIR",
        "close_btn": "CERRAR",
        "ready": "Listo.",
        "working": "Trabajando...",
        "canceling": "Cancelando...",
        "empty_title": "Vacio",
        "empty_body": "No hay addons marcados.",
        "no_dest_title": "Falta destino",
        "no_dest_body": "Escribe o elige la carpeta destino.",
        "not_found_title": "No existe",
        "not_found_body": "No se encuentra:\n{path}",
        "no_log_title": "Log",
        "no_log_body": "Todavia no hay archivo de log.",
        "rename_title": "Renombrar",
        "rename_prompt": "Nuevo nombre:",
        "rename_all_title": "Renombrar todo",
        "rename_all_prompt": "Patron (usa {i} para indice, {name} para nombre viejo):",
        "action_title": "Accion",
        "action_body": "Addon: {name}\n\nSi = Renombrar\nNo = Extraer a temporal y abrir\nCancelar = Nada",
        "dest_missing_title": "No existe",
        "conflicts_need_title": "Conflictos",
        "conflicts_need_body": "Marca al menos 2 addons.",
        "conflicts_none_title": "Conflictos",
        "conflicts_none_body": "Sin conflictos entre los marcados.",
        "summary_empty_title": "Resumen",
        "summary_empty_body": "Aun no has analizado nada.",
        "export_empty_title": "Exportar",
        "export_empty_body": "No hay addons.",
        "save_as_title": "Guardar como",
        "zip_error_title": "Error al leer zip",
        "error_title": "Error",
        "url_title": "Descargar de Workshop",
        "url_prompt": "Pega la URL de Steam Workshop:",
        "url_bad_body": "No se encontro ID de Workshop en esa URL.",
        "url_ok": "Descargado: {name}",
        "url_no_file": "Steam no dio URL de descarga para este item.",
        "grep_title": "Buscar dentro de addons",
        "grep_prompt": "Texto a buscar:",
        "grep_empty": "Sin coincidencias.",
        "grep_done": "{n} coincidencia(s) en {m} addon(s).",
        "repack_title": "Repack a GMA",
        "repack_prompt": "Archivo .gma destino:",
        "repack_need_folder": "Selecciona exactamente una carpeta para repackear.",
        "backup_title": "Backup",
        "backup_done": "{n} addon(s) respaldados en {path}.",
        "watch_title": "Vigilar carpeta",
        "watch_prompt": "Elige la carpeta a vigilar:",
        "watch_started": "Vigilando: {path}",
        "watch_stopped": "Vigilancia detenida.",
        "watch_new": "Nuevo archivo: {name}",
        "whitelist_title": "Whitelist de Workshop",
        "whitelist_body": "IDs permitidos (uno por linea):",
        "collections_title": "Colecciones",
        "collections_save": "Guardar lista actual",
        "collections_load": "Cargar coleccion",
        "collections_name": "Nombre de la coleccion:",
        "collections_saved": "Guardada: {name}",
        "collections_empty": "Sin colecciones guardadas.",
        "report_done": "Reporte guardado: {path}",
        "sizes_title": "Desglose de tamaños",
        "fastdl_title": "Export FastDL",
        "fastdl_prompt": "Elige la carpeta raiz de FastDL:",
        "fastdl_done": "{n} asset(s) copiados a {path}.",
        "gmod_open_title": "Garry's Mod parece estar abierto",
        "gmod_open_body": "GMod deberia estar cerrado antes de modificar addons. Continuar de todos modos?",
        "status_analyzing": "Analizando {i}/{total}: {name}",
        "status_scanning": "Escaneando {i}/{total}: {name}",
        "status_extracting": "Extrayendo {i}/{total}: {name}",
        "status_indexing": "Indexando {i}/{total}: {name}",
        "status_analysis_ok": "Analisis completo: {n} addon(s)",
        "status_analysis_partial": "Analisis: {ok} ok, {fail} errores",
        "status_analysis_cancelled": "Analisis cancelado: {n}/{total}",
        "status_extract_ok": "Extraccion completa: {n} addon(s)",
        "status_extract_partial": "Extraccion: {ok} ok, {fail} fallos",
        "status_extract_cancelled": "Extraccion cancelada: {ok} ok, {fail} fallos",
        "status_index_ok": "Indexado completo: {n} addon(s)",
        "status_index_cancelled": "Indexado cancelado: {n} addon(s)",
        "status_conflicts_none": "Conflictos: ninguno",
        "status_conflicts_found": "Conflictos: {n} archivo(s)",
        "status_selected_all": "Marcados {n} addon(s)",
        "status_deselected_all": "Desmarcados {n} addon(s)",
        "status_inverted": "Seleccion invertida: {sel} marcados",
        "status_removed": "Quitados {n} addon(s)",
        "status_cleared": "Lista limpiada ({n} eliminados)",
        "status_exported": "Exportado: {name}",
        "status_session": "Sesion: {n} addon(s)",
        "status_added_zip": "{name}: {n} addon(s)",
        "status_no_op": "No hay operacion en curso.",
        "status_cancel_requested": "Cancelacion solicitada...",
    },
}
